from fastapi import FastAPI, HTTPException
from typing import List

app = FastAPI()

events_data = [
    {
        "id": 1,
        "name": "Tech Conference 2025",
        "location": "San Francisco, CA",
        "date": "2025-06-15",
        "time": "10:00 AM",
        "tickets_available": 150,
        "price": 99.99,
        "currency": "USD",
        "status": "Available",
        "organizer": "Tech World Inc.",
        "category": "Technology",
        "description": "A conference for tech enthusiasts covering AI, Web3, and more.",
    },
    {
        "id": 2,
        "name": "Jazz Festival 2025",
        "location": "New Orleans, LA",
        "date": "2025-07-22",
        "time": "6:00 PM",
        "tickets_available": 200,
        "price": 49.99,
        "currency": "USD",
        "status": "Available",
        "organizer": "Jazz Association",
        "category": "Music",
        "description": "Enjoy live jazz performances from world-renowned artists.",
    },
    {
        "id": 3,
        "name": "Blockchain Summit",
        "location": "New York, NY",
        "date": "2025-08-10",
        "time": "9:00 AM",
        "tickets_available": 80,
        "price": 129.99,
        "currency": "USD",
        "status": "Sold Out",
        "organizer": "Crypto Innovations",
        "category": "Finance",
        "description": "A deep dive into blockchain, DeFi, and the future of crypto.",
    },
    {
        "id": 4,
        "name": "Food & Wine Festival",
        "location": "Napa Valley, CA",
        "date": "2025-09-12",
        "time": "11:00 AM",
        "tickets_available": 300,
        "price": 79.99,
        "currency": "USD",
        "status": "Available",
        "organizer": "Gourmet Experiences LLC",
        "category": "Food & Drink",
        "description": "Sample exquisite wines and gourmet dishes from top chefs and wineries.",
    },
    {
        "id": 5,
        "name": "Marathon 2025",
        "location": "Chicago, IL",
        "date": "2025-10-08",
        "time": "7:00 AM",
        "tickets_available": 10000,
        "price": 120.00,
        "currency": "USD",
        "status": "Available",
        "organizer": "Run Nation",
        "category": "Sports",
        "description": "Annual city marathon with routes through Chicago's most scenic neighborhoods.",
    },
    {
        "id": 6,
        "name": "Digital Art Exhibition",
        "location": "Miami, FL",
        "date": "2025-11-15",
        "time": "10:00 AM",
        "tickets_available": 500,
        "price": 25.50,
        "currency": "USD",
        "status": "Available",
        "organizer": "Modern Art Collective",
        "category": "Art",
        "description": "Immersive digital art experience featuring works from emerging NFT artists.",
    },
    {
        "id": 7,
        "name": "Startup Pitch Competition",
        "location": "Austin, TX",
        "date": "2025-05-20",
        "time": "1:00 PM",
        "tickets_available": 150,
        "price": 45.00,
        "currency": "USD",
        "status": "Limited Availability",
        "organizer": "Venture Capital Network",
        "category": "Business",
        "description": "Watch promising startups pitch to top investors for funding opportunities.",
    },
    {
        "id": 8,
        "name": "Yoga Retreat",
        "location": "Sedona, AZ",
        "date": "2025-04-05",
        "time": "8:00 AM",
        "tickets_available": 30,
        "price": 299.99,
        "currency": "USD",
        "status": "Available",
        "organizer": "Mindful Living",
        "category": "Wellness",
        "description": "Weekend retreat with daily yoga sessions, meditation, and healthy meals.",
    },
    {
        "id": 9,
        "name": "Comedy Night Special",
        "location": "New York, NY",
        "date": "2025-08-22",
        "time": "8:30 PM",
        "tickets_available": 200,
        "price": 35.75,
        "currency": "USD",
        "status": "Available",
        "organizer": "Laugh Factory",
        "category": "Entertainment",
        "description": "An evening of stand-up comedy featuring top comedians from Netflix specials.",
    },
    {
        "id": 10,
        "name": "Science Fair Expo",
        "location": "Boston, MA",
        "date": "2025-03-30",
        "time": "9:00 AM",
        "tickets_available": 400,
        "price": 15.00,
        "currency": "USD",
        "status": "Available",
        "organizer": "STEM Education Foundation",
        "category": "Education",
        "description": "Interactive science exhibits and workshops for all ages.",
    },
    {
        "id": 11,
        "name": "Film Festival",
        "location": "Park City, UT",
        "date": "2025-01-18",
        "time": "10:00 AM",
        "tickets_available": 1000,
        "price": 50.00,
        "currency": "USD",
        "status": "Early Bird",
        "organizer": "Independent Cinema Guild",
        "category": "Film",
        "description": "Premieres of independent films with Q&A sessions with directors.",
    },
    {
        "id": 12,
        "name": "Gaming Tournament",
        "location": "Las Vegas, NV",
        "date": "2025-07-05",
        "time": "12:00 PM",
        "tickets_available": 800,
        "price": 65.25,
        "currency": "USD",
        "status": "Available",
        "organizer": "eSports United",
        "category": "Gaming",
        "description": "National championship for popular competitive video games with cash prizes.",
    },
    {
        "id": 13,
        "name": "Literary Festival",
        "location": "Portland, OR",
        "date": "2025-09-28",
        "time": "10:00 AM",
        "tickets_available": 350,
        "price": 29.99,
        "currency": "USD",
        "status": "Available",
        "organizer": "Bookworms Society",
        "category": "Literature",
        "description": "Meet famous authors, attend readings, and participate in writing workshops.",
    },
    {
        "id": 14,
        "name": "Sustainable Living Expo",
        "location": "Seattle, WA",
        "date": "2025-04-22",
        "time": "9:30 AM",
        "tickets_available": 600,
        "price": 20.00,
        "currency": "USD",
        "status": "Available",
        "organizer": "Green Future Initiative",
        "category": "Environment",
        "description": "Learn about eco-friendly technologies and sustainable living practices.",
    },
    {
        "id": 15,
        "name": "Broadway Musical",
        "location": "New York, NY",
        "date": "2025-12-05",
        "time": "7:30 PM",
        "tickets_available": 50,
        "price": 149.99,
        "currency": "USD",
        "status": "Limited Availability",
        "organizer": "Great White Way Productions",
        "category": "Theater",
        "description": "Tony Award-winning musical with original cast members.",
    },
]


@app.get("/api/events", response_model=List[dict])
async def get_events():
    return events_data


@app.get("/api/events/{event_id}", response_model=dict)
async def get_event(event_id: int):
    event = next((e for e in events_data if e["id"] == event_id), None)
    if not event:
        raise HTTPException(status_code=404, detail="Event not found")
    return event
